### ISSUE TITLE
close with strg + q give segv in read_notes()

### ISSUE THREAD

**Issue by jf-simon** [jf-simon/enotes#2]

**Comment by jf-simon** [comment]
Starting program: /opt/efl/bin/enotes 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4922700 (LWP 7757)]
[New Thread 0x7fffe182a700 (LWP 7758)]
[Thread 0x7fffe182a700 (LWP 7758) exited]
[New Thread 0x7fffd4e94700 (LWP 7759)]
[New Thread 0x7fffd3c2d700 (LWP 7760)]
[Thread 0x7fffd3c2d700 (LWP 7760) exited]
[New Thread 0x7fffd3c2d700 (LWP 7761)]
[Thread 0x7fffd4e94700 (LWP 7759) exited]
[Thread 0x7fffe4922700 (LWP 7757) exited]
[Thread 0x7fffd3c2d700 (LWP 7761) exited]
[Inferior 1 (process 7756) exited normally]
No stack.
Starting program: /opt/efl/bin/enotes 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4922700 (LWP 7784)]
[New Thread 0x7fffe182a700 (LWP 7785)]
[Thread 0x7fffe182a700 (LWP 7785) exited]
[New Thread 0x7fffd4e94700 (LWP 7786)]
[New Thread 0x7fffd3c2d700 (LWP 7787)]
[Thread 0x7fffd3c2d700 (LWP 7787) exited]
[New Thread 0x7fffd3c2d700 (LWP 7788)]
[Thread 0x7fffd4e94700 (LWP 7786) exited]
[Thread 0x7fffe4922700 (LWP 7784) exited]
[Thread 0x7fffd3c2d700 (LWP 7788) exited]
[Inferior 1 (process 7783) exited normally]
No stack.
Starting program: /opt/efl/bin/enotes 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4922700 (LWP 7792)]
[New Thread 0x7fffe182a700 (LWP 7793)]
[Thread 0x7fffe182a700 (LWP 7793) exited]
[New Thread 0x7fffd4e94700 (LWP 7794)]
[New Thread 0x7fffd3c2d700 (LWP 7797)]
[Thread 0x7fffd3c2d700 (LWP 7797) exited]
[New Thread 0x7fffd3c2d700 (LWP 7798)]
[Thread 0x7fffd4e94700 (LWP 7794) exited]
[Thread 0x7fffe4922700 (LWP 7792) exited]
[Thread 0x7fffd3c2d700 (LWP 7798) exited]
[Inferior 1 (process 7791) exited normally]
Starting program: /opt/efl/bin/enotes 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4922700 (LWP 7801)]
[New Thread 0x7fffe182a700 (LWP 7802)]
[Thread 0x7fffe182a700 (LWP 7802) exited]

Thread 1 "enotes" received signal SIGSEGV, Segmentation fault.
0x000055555555935e in _read_notes ()
#0  0x000055555555935e in _read_notes ()
#1  0x000055555555fa7e in elm_main ()
#2  0x000055555555fe6a in main ()
#0  0x000055555555935e in _read_notes ()

**Comment by jf-simon** [comment]
fix by using confirm popup
